### ISSUE TITLE
Prokka not outputting gbk files

### ISSUE THREAD

**Issue by Lamm-a** [tseemann/prokka#457] opened 2020-01-21 15:01 UTC
I am running prokka on some host associated bacter whole genome sequences using the following command:
`prokka --outdir $outdir --prefix $prefix $assembly`

The run seems to be executing fine with the outlgs showing no errors but no gbk files are being created at the end of the run. The tail of the log report looks like this:
```

[12:04:40] Fixed 748 colliding /gene names.
[12:04:40] Adding /locus_tag identifiers
[12:04:40] Assigned 9701 locus_tags to CDS and RNA features.
[12:04:40] Writing outputs to /home/lamma/faststorage/actinobacteria/comparison_sequences/annotated/Amycolatopsis_sp._YIM_10/
[12:04:44] Generating annotation statistics file
[12:04:44] Generating Genbank and Sequin files
[12:04:44] Running: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.14.5 from https://github.com/tseemann/prokka' -Z \/home\/lamma\/faststorage\/actinobacteria\/comparison_sequences\/annotated\/Amycolatopsis_sp\._YIM_10\/Amycolatopsis_sp\._YIM_10\.err -i \/home\/lamma\/faststorage\/actinobacteria\/comparison_sequences\/annotated\/Amycolatopsis_sp\._YIM_10\/Amycolatopsis_sp\._YIM_10\.fsa 2> /dev/null
[12:05:05] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.14.5 from https://github.com/tseemann/prokka' -Z \/home\/lamma\/faststorage\/actinobacteria\/comparison_sequences\/annotated\/Amycolatopsis_sp\._YIM_10\/Amycolatopsis_sp\._YIM_10\.err -i \/home\/lamma\/faststorage\/actinobacteria\/comparison_sequences\/annotated\/Amycolatopsis_sp\._YIM_10\/Amycolatopsis_sp\._YIM_10\.fsa 2> /dev/null
```

So it is stating it is generating the gbk files but the outdir does not contain them.
Any idea what the issue may be here?

**Comment by zdk123** [comment] 2020-01-21 19:20
clearly a duplicate of issue #453

**Comment by tseemann** [comment] 2020-01-23 00:14
Yep. it's tbl2asn problem.

**Closed by tseemann** 2020-01-23 00:14 UTC
Labels: duplicate
