### ISSUE TITLE
Could not run command: tbl2asn

### ISSUE THREAD

**Issue by lucaspompeun** [tseemann/prokka#461] opened 2020-01-31 18:02 UTC
Running prokka today I've had this problem with tbl2asn

```
[12:20:50] Generating Genbank and Sequin files 

[12:20:50] Running: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.13.3 from https://github.com/tseemann/prokka' -Z projects\/SRR2014554_teste\/prokka\/\/SRR2014554_teste \.err -i projects\/SRR2014554_teste\/prokka\/\/SRR2014554_teste\.fsa 2> /dev/null 

[12:21:25] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.13.3 from https://github.com/tseemann/prokka' -Z projects\/SRR2014554_teste\/prokka\/\/SR R2014554_teste\.err -i projects\/SRR2014554_teste\/prokka\/\/SRR2014554_teste\.fsa 2> /dev/null
```

**Comment by nahanoo** [comment] 2020-02-03 09:35
Dear lucas,
This issue is a duplicate of #453. Hopefully you can figure out a working solution based on this issue.
Best

**Closed** 2020-02-05 16:38 UTC
